import { createPublicClient, createWalletClient, http, getContract } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { hardhat } from "viem/chains";
import { readFileSync } from "fs";

// ── ABI imports (generated by Hardhat compile) ────────────────────────────────

import DIDRegistryABI         from "../../artifacts/contracts/DIDRegistry.sol/DIDRegistry.json" assert { type: "json" };
import DocumentRegistryABI    from "../../artifacts/contracts/DocumentRegistry.sol/DocumentRegistry.json" assert { type: "json" };
import DocumentAccessControlABI from "../../artifacts/contracts/DocumentAccessControl.sol/DocumentAccessControl.json" assert { type: "json" };
import KeyShareRegistryABI    from "../../artifacts/contracts/KeyShareRegistry.sol/KeyShareRegistry.json" assert { type: "json" };
import GovernanceContractABI  from "../../artifacts/contracts/GovernanceContract.sol/GovernanceContract.json" assert { type: "json" };
import AuditLogABI            from "../../artifacts/contracts/AuditLog.sol/AuditLog.json" assert { type: "json" };

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ContractAddresses {
  auditLog:           `0x${string}`;
  didRegistry:        `0x${string}`;
  governanceContract: `0x${string}`;
  documentRegistry:   `0x${string}`;
  accessControl:      `0x${string}`;
  keyShareRegistry:   `0x${string}`;
}

export interface ContractClients {
  publicClient:  ReturnType<typeof createPublicClient>;
  walletClient:  ReturnType<typeof createWalletClient>;
  addresses:     ContractAddresses;
  didRegistry:   ReturnType<typeof getContract>;
  documentRegistry: ReturnType<typeof getContract>;
  accessControl: ReturnType<typeof getContract>;
  keyShareRegistry: ReturnType<typeof getContract>;
  governance:    ReturnType<typeof getContract>;
  auditLog:      ReturnType<typeof getContract>;
}

// ── Chain configuration ───────────────────────────────────────────────────────

/**
 * Build a viem chain config for a Ganache/Hardhat node at the given RPC URL.
 * We reuse the hardhat chain id (31337) for local development.
 */
function buildChain(rpcUrl: string) {
  return {
    ...hardhat,
    rpcUrls: {
      default: { http: [rpcUrl] },
      public:  { http: [rpcUrl] },
    },
  };
}

// ── Initialisation ────────────────────────────────────────────────────────────

/**
 * Initialise viem clients and contract instances.
 *
 * @param rpcUrl        JSON-RPC endpoint of the consortium blockchain node.
 * @param privateKeyHex Authority node's Ethereum private key (hex, no 0x prefix).
 * @param addressesPath Path to addresses.json written by the deploy script.
 */
export function initContracts(
  rpcUrl:        string,
  privateKeyHex: string,
  addressesPath: string
): ContractClients {
  const raw       = readFileSync(addressesPath, "utf-8");
  const addresses = JSON.parse(raw) as ContractAddresses;

  const chain   = buildChain(rpcUrl);
  const account = privateKeyToAccount(`0x${privateKeyHex}` as `0x${string}`);

  const publicClient = createPublicClient({ chain, transport: http(rpcUrl) });
  const walletClient = createWalletClient({ chain, transport: http(rpcUrl), account });

  const shared = { client: publicClient, chain, account };

  const didRegistry = getContract({
    address: addresses.didRegistry,
    abi:     DIDRegistryABI.abi,
    client:  { public: publicClient, wallet: walletClient },
  });

  const documentRegistry = getContract({
    address: addresses.documentRegistry,
    abi:     DocumentRegistryABI.abi,
    client:  { public: publicClient, wallet: walletClient },
  });

  const accessControl = getContract({
    address: addresses.accessControl,
    abi:     DocumentAccessControlABI.abi,
    client:  { public: publicClient, wallet: walletClient },
  });

  const keyShareRegistry = getContract({
    address: addresses.keyShareRegistry,
    abi:     KeyShareRegistryABI.abi,
    client:  { public: publicClient, wallet: walletClient },
  });

  const governance = getContract({
    address: addresses.governanceContract,
    abi:     GovernanceContractABI.abi,
    client:  { public: publicClient, wallet: walletClient },
  });

  const auditLog = getContract({
    address: addresses.auditLog,
    abi:     AuditLogABI.abi,
    client:  { public: publicClient, wallet: walletClient },
  });

  return {
    publicClient,
    walletClient,
    addresses,
    didRegistry,
    documentRegistry,
    accessControl,
    keyShareRegistry,
    governance,
    auditLog,
  };
}

// ── DIDRegistry helpers ───────────────────────────────────────────────────────

export async function resolveDID(
  contracts: ContractClients,
  did: string
) {
  return contracts.didRegistry.read.resolve([did]) as Promise<any>;
}

export async function lookupDID(
  contracts: ContractClients,
  address: `0x${string}`
): Promise<string> {
  return contracts.didRegistry.read.lookupDID([address]) as Promise<string>;
}

export async function getActivePublicKey(
  contracts: ContractClients,
  did: string
): Promise<string> {
  return contracts.didRegistry.read.getActivePublicKey([did]) as Promise<string>;
}

export async function isFullyActive(
  contracts: ContractClients,
  did: string
): Promise<boolean> {
  return contracts.didRegistry.read.isFullyActive([did]) as Promise<boolean>;
}

// ── DocumentRegistry helpers ──────────────────────────────────────────────────

export async function getRecord(
  contracts: ContractClients,
  documentHash: `0x${string}`
) {
  return contracts.documentRegistry.read.getRecord([documentHash]) as Promise<any>;
}

export async function getDocumentStatus(
  contracts: ContractClients,
  documentHash: `0x${string}`
): Promise<number> {
  return contracts.documentRegistry.read.getStatus([documentHash]) as Promise<number>;
}

export async function certifyDocument(
  contracts: ContractClients,
  documentHash: `0x${string}`,
  signature: `0x${string}`
): Promise<`0x${string}`> {
  return contracts.documentRegistry.write.certify([documentHash, signature]) as Promise<`0x${string}`>;
}

export async function storeCID(
  contracts: ContractClients,
  documentHash: `0x${string}`,
  cid: string
): Promise<`0x${string}`> {
  return contracts.documentRegistry.write.storeCID([documentHash, cid]) as Promise<`0x${string}`>;
}

// ── KeyShareRegistry helpers ──────────────────────────────────────────────────

export async function storeShares(
  contracts:           ContractClients,
  documentHash:        `0x${string}`,
  authorityAddresses:  `0x${string}`[],
  shareIndices:        bigint[],
  encryptedShares:     `0x${string}`[],
  threshold:           bigint,
  encryptedKey:        `0x${string}`   
): Promise<`0x${string}`> {
  return contracts.keyShareRegistry.write.storeShares([
    documentHash,
    authorityAddresses,
    shareIndices,
    encryptedShares,
    threshold,
    encryptedKey,    
  ]) as Promise<`0x${string}`>;
}

export async function getShare(
  contracts:        ContractClients,
  documentHash:     `0x${string}`,
  authorityAddress: `0x${string}`
): Promise<{ shareIndex: bigint; authorityAddress: `0x${string}`; encryptedShare: `0x${string}` }> {
  return contracts.keyShareRegistry.read.getShare([
    documentHash,
    authorityAddress,
  ]) as Promise<any>;
}

export async function getThreshold(
  contracts:    ContractClients,
  documentHash: `0x${string}`
): Promise<bigint> {
  return contracts.keyShareRegistry.read.getThreshold([documentHash]) as Promise<bigint>;
}

export async function getEncryptedKey(
  contracts:    ContractClients,
  documentHash: `0x${string}`
): Promise<`0x${string}`> {
  return contracts.keyShareRegistry.read.getEncryptedKey([documentHash]) as Promise<`0x${string}`>;
}

// ── GovernanceContract helpers ────────────────────────────────────────────────

export async function getAuthorities(
  contracts: ContractClients
): Promise<`0x${string}`[]> {
  return contracts.governance.read.getAuthorities([]) as Promise<`0x${string}`[]>;
}

// ── AuditLog helpers ──────────────────────────────────────────────────────────

/**
 * Fetch ReadApproved events for a specific document hash.
 * Used by authority nodes to verify that a user has been granted
 * read access before releasing a key share.
 */
export async function getReadApprovedEvents(
  contracts:    ContractClients,
  documentHash: `0x${string}`,
  fromBlock:    bigint = 0n
) {
  return contracts.publicClient.getContractEvents({
    address:   contracts.addresses.auditLog,
    abi:       AuditLogABI.abi,
    eventName: "EntryLogged",
    fromBlock,
  });
}

/**
 * Fetch ReadApproved events directly from DocumentAccessControl.
 * More precise than AuditLog — filters by document hash and user address.
 */
export async function getReadApprovedEventsFromDAC(
  contracts:    ContractClients,
  documentHash: `0x${string}`,
  userAddress:  `0x${string}`,
  fromBlock:    bigint = 0n
) {
  return contracts.publicClient.getContractEvents({
    address:   contracts.addresses.accessControl,
    abi:       DocumentAccessControlABI.abi,
    eventName: "ReadApproved",
    args: {
      userAddress,
      documentHash,
    },
    fromBlock,
  });
}