import { network } from "hardhat";
import { writeFileSync, mkdirSync, readFileSync } from "fs";
import { join } from "path";

async function main() {
  const { viem } = await network.connect();
  const [deployer, authorityA, authorityB, authorityC] =
    await viem.getWalletClients();

  console.log("Deployer:    ", deployer.account.address);
  console.log("Authority A: ", authorityA.account.address);
  console.log("Authority B: ", authorityB.account.address);
  console.log("Authority C: ", authorityC.account.address);

  // ── 1. Deploy AuditLog ───────────────────────────────────────────────────
  console.log("\n[1/6] Deploying AuditLog...");
  const auditLog = await viem.deployContract("AuditLog");
  console.log("AuditLog:             ", auditLog.address);

  // ── 2. Deploy DIDRegistry ────────────────────────────────────────────────
  console.log("\n[2/6] Deploying DIDRegistry...");

  // Read RSA public keys generated by authority containers before deploy.
  // In Docker: written to /shared by authority-*-keygen containers.
  // Locally: fallback to placeholder strings for development.
  let activeKeys:   string[];
  let recoveryKeys: string[];

  try {
    const pkA = readFileSync("/shared/pk-authority-a.pem", "utf-8");
    const pkB = readFileSync("/shared/pk-authority-b.pem", "utf-8");
    const pkC = readFileSync("/shared/pk-authority-c.pem", "utf-8");
    activeKeys   = [pkA, pkB, pkC];
    recoveryKeys = [pkA, pkB, pkC]; // same key for prototype
    console.log("RSA public keys loaded from /shared");
  } catch {
    console.warn("RSA keys not found in /shared — using placeholders (local dev)");
    activeKeys   = ["pk-a-placeholder", "pk-b-placeholder", "pk-c-placeholder"];
    recoveryKeys = ["rk-a-placeholder", "rk-b-placeholder", "rk-c-placeholder"];
  }

  const authorities = [
    authorityA.account.address,
    authorityB.account.address,
    authorityC.account.address,
  ];
  const dids = [
    "did:consortium:authority-a",
    "did:consortium:authority-b",
    "did:consortium:authority-c",
  ];

  const didRegistry = await viem.deployContract("DIDRegistry", [
    authorities,
    dids,
    activeKeys,
    recoveryKeys,
    auditLog.address,
  ]);
  console.log("DIDRegistry:          ", didRegistry.address);

  // ── 3. Deploy GovernanceContract ─────────────────────────────────────────
  console.log("\n[3/6] Deploying GovernanceContract...");
  const governance = await viem.deployContract("GovernanceContract", [
    authorities,
    dids,
    didRegistry.address,
    auditLog.address,
  ]);
  console.log("GovernanceContract:   ", governance.address);

  // ── 4. Deploy DocumentRegistry ───────────────────────────────────────────
  console.log("\n[4/6] Deploying DocumentRegistry...");
  const documentRegistry = await viem.deployContract("DocumentRegistry", [
    didRegistry.address,
    auditLog.address,
  ]);
  console.log("DocumentRegistry:     ", documentRegistry.address);

  // ── 5. Deploy DocumentAccessControl ──────────────────────────────────────
  console.log("\n[5/6] Deploying DocumentAccessControl...");
  const accessControl = await viem.deployContract("DocumentAccessControl", [
    didRegistry.address,
    documentRegistry.address,
    auditLog.address,
  ]);
  console.log("DocumentAccessControl:", accessControl.address);

  // ── 6. Deploy KeyShareRegistry ────────────────────────────────────────────
  console.log("\n[6/6] Deploying KeyShareRegistry...");
  const keyShareRegistry = await viem.deployContract("KeyShareRegistry", [
    didRegistry.address,
    auditLog.address,
  ]);
  console.log("KeyShareRegistry:     ", keyShareRegistry.address);

  // ── Wire up contracts ────────────────────────────────────────────────────
  console.log("\n[Setup] Wiring contracts...");

  const sleep = (ms: number) => new Promise(r => setTimeout(r, ms));

  async function sendTx(fn: () => Promise<`0x${string}`>, label: string) {
    for (let attempt = 1; attempt <= 5; attempt++) {
      try {
        const hash = await fn();
        console.log(`  ✓ ${label}`);
        return hash;
      } catch (e: any) {
        console.warn(`  ✗ ${label} (attempt ${attempt}/5): ${e.shortMessage ?? e.message}`);
        if (attempt < 5) await sleep(2000 * attempt);
        else throw e;
      }
    }
  }

  await sendTx(() => didRegistry.write.setGovernanceContract([governance.address]), "didRegistry.setGovernanceContract");
  await sendTx(() => didRegistry.write.setAccessControl([accessControl.address]), "didRegistry.setAccessControl");
  await sendTx(() => documentRegistry.write.setAccessControl([accessControl.address]), "documentRegistry.setAccessControl");
  await sendTx(() => documentRegistry.write.setGovernanceContract([governance.address]), "documentRegistry.setGovernanceContract");
  await sendTx(() => accessControl.write.setGovernanceContract([governance.address]), "accessControl.setGovernanceContract");

  await sendTx(() => auditLog.write.addWriter([didRegistry.address]), "auditLog.addWriter(didRegistry)");
  await sendTx(() => auditLog.write.addWriter([governance.address]), "auditLog.addWriter(governance)");
  await sendTx(() => auditLog.write.addWriter([documentRegistry.address]), "auditLog.addWriter(documentRegistry)");
  await sendTx(() => auditLog.write.addWriter([accessControl.address]), "auditLog.addWriter(accessControl)");
  await sendTx(() => auditLog.write.addWriter([keyShareRegistry.address]), "auditLog.addWriter(keyShareRegistry)");
  await sendTx(() => auditLog.write.renounceAdmin(), "auditLog.renounceAdmin");

  console.log("AuditLog writers frozen.");

  // ── Register test user ───────────────────────────────────────────────────
  console.log("\n[Setup] Registering test user...");

  const [,,,, userAccount] = await viem.getWalletClients();

  let userPublicKey: string;
  try {
    userPublicKey = readFileSync("/shared/user-public.pem", "utf-8");
    console.log("User RSA public key loaded from /shared");
  } catch {
    userPublicKey = "pk-user-placeholder";
    console.warn("User RSA key not found — using placeholder");
  }

  await sendTx(
    () => didRegistry.write.registerUser(
      [
        "did:consortium:user-1",
        userPublicKey,
        userPublicKey,
        userAccount.account.address,
        0n,
      ],
      { account: authorityA.account }
    ),
    "didRegistry.registerUser(user-1)"
  );
  console.log("Test user registered.");

  // ── Save addresses ───────────────────────────────────────────────────────
  const addresses = {
    auditLog:           auditLog.address,
    didRegistry:        didRegistry.address,
    governanceContract: governance.address,
    documentRegistry:   documentRegistry.address,
    accessControl:      accessControl.address,
    keyShareRegistry:   keyShareRegistry.address,
    authorities: {
      a: authorityA.account.address,
      b: authorityB.account.address,
      c: authorityC.account.address,
    },
    dids: {
      a: dids[0],
      b: dids[1],
      c: dids[2],
    },
  };

  try {
    mkdirSync("/shared", { recursive: true });
    writeFileSync("/shared/addresses.json", JSON.stringify(addresses, null, 2));
    console.log("Addresses written to /shared/addresses.json");
  } catch {
    // Running locally
  }

  writeFileSync(
    join(process.cwd(), "scripts", "addresses.json"),
    JSON.stringify(addresses, null, 2)
  );
  console.log("Addresses written to scripts/addresses.json");
  console.log("\nDeployment complete.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});